version: '3.3'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-shared_db}
      - POSTGRES_USER=${DB_USERNAME:-app_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-app_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 